name: Builds and publishes release versions of the binary.

on:
  push:
    tags:
      - 'v.*.*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install Go Dependencies
        run: go get .

      - name: Build Linux Release Version
        run: go build -ldflags "-s -w" -o genwgconfs_linux-amd64

      - name: Build Windows Release Version
        run: go build -ldflags "-s -w" -o genwgconfs_windows-amd64.exe
        env:
          GOOS: windows

      - name: Publish Binaries
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            genwgconfs_linux-amd64
            genwgconfs_windows-amd64.exe
